### ISSUE TITLE
an…Emmmmm，你不来MSS吗……

### ISSUE THREAD

**Issue by David-Xian66** [Anschluss-zeit/MCBBS_Auto_SignIn#1]
（没办法，你即时通讯软件用不了，，我只能在这里发……

**Comment by David-Xian66** [comment]
你要是不想的话，也没关系，我不强求……

**Comment by Ark-Aak** [comment]
> 你要是不想的话，也没关系，我不强求……

6，我以为你们把我踢了.jpg

**Comment by David-Xian66** [comment]
> > 你要是不想的话，也没关系，我不强求……
> 
> 6，我以为你们把我踢了.jpg

没有，QQ那个群是这样的，因为你那个号不是不在你手里吗，QHQQI怕当时某人看见群消息，更生气了，所以就先踢了。到时候你号回来了，马上给拉回来
